dtmui:
    resource: "@DTMUIBundle/Resources/config/routing.yml"
    prefix:   /

dtm_task_db:
    resource: "@DTMTaskDBBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
